[package]
name = "protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
types = { path = "../types" }
libp2p = { workspace = true }
libp2p-request-response = { workspace = true }
generated = { path = "../generated" }
