global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8889"]
  - job_name: "etcd"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "etcd-etcd-00-1:2381"
          - "etcd-etcd-01-1:2381"
          - "etcd-etcd-02-1:2381"
